spacing = 1
padding = 0
hide_ascii = false 
separator = "|"
separator_color = "006"
key_color = "005"

[palette]
glyph = " "
visible = true
type = "Light"

[bar]
visible = true
glyph = "󰨐"
symbol_open = '['
symbol_close = ']'
hide_delimiters = false 

[box]
title = " / madeinheaven91 󱔎 / "
border = "rounded"
visible = true

[custom_ascii]
color = "006"
path = "~/.config/macchina/themes/ascii"
