#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          0

bspc config focused_border_color        "#eb6f92"
bspc config normal_border_color         "#232136"
bspc config active_border_color         "#eb6f92"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true

bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a Viewnior state=floating
bspc rule -a nekobox state=floating
bspc rule -a nekoray state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a pavucontrol state=floating
bspc rule -a krita state=floating
bspc rule -a python3 state=floating
bspc rule -a Blueman-manager state=floating follow=on
bspc rule -a qBittorrent state=floating follow=on
# bspc rule -a "TelegramDesktop:*:Media viewer" state=floating follow=on
# bspc rule -a "*:*:Media viewer" state=floating follow=on
# bspc rule -a TelegramDesktop:*:* state=floating follow=on

for_window [class="Telegram" title="Media viewer"] floating enable

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Environment variables
export QT_QPA_PLATFORMTHEME=qt5ct
export EDITOR=nvim

# Autostart
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --set-zoom-fill --random ~/Pictures/Wallpapers &
dunst &
nm-applet --indicator &
# blueman-manager &
nekoray &
exec xset r rate 150 30 &
sh /home/madeinheaven91/.config/polybar/launch.sh --material &
sh /home/madeinheaven91/autostart.sh &
picom --config /home/madeinheaven91/.config/picom/picom.conf &
