interface = "wlan0"
long_uptime = true
long_shell = false
long_kernel = false
current_shell = true
physical_cores = false
theme = "Main"

show = ["Machine", "Distribution", "DesktopEnvironment", "Terminal", "Shell", "Uptime", "Resolution", "Processor", ]
